<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace> Drawie.Layer.ThreeD.Test</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Drawie.RenderApi.OpenGl\Drawie.RenderApi.OpenGl.csproj" />
      <ProjectReference Include="..\Drawie.Windowing\Drawie.Windowing.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Shaders\**.glsl" />
      <Content Include="Shaders\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
        <None Remove="Images\**.glsl" />
        <Content Include="Images\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
