<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!--<WarningsAsErrors>CS8600;CS8601;CS8602;CS8604;CS8613;CS8614;CS8619;CS8620;CS8622;CS8625;CS8629;CS8633;CS8524;CS8509;CS8524;CS8767</WarningsAsErrors><!-->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Drawie.Numerics\Drawie.Numerics.csproj" />
    <ProjectReference Include="..\Drawie.RenderApi\Drawie.RenderApi.csproj" />
  </ItemGroup>

</Project>
