<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DrawieSample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Drawie2Sample\Drawie2Sample.csproj" />
    <ProjectReference Include="..\DrawiEngine.Desktop\DrawiEngine.Desktop.csproj" />
    <ProjectReference Include="..\DrawiEngine\DrawiEngine.csproj" />
  </ItemGroup>
</Project>
