<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Drawie2Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Drawie.Backend.Vertie\Drawie.Backend.Vertie.csproj" />
        <ProjectReference Include="..\Drawie.Layer.3D.Test\Drawie.Layer.3D.Test.csproj" />
        <ProjectReference Include="..\Drawie.Layer.UI.ImGui\Drawie.Layer.UI.ImGui.csproj" />
        <ProjectReference Include="..\DrawiEngine\DrawiEngine.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="Images\dancing-dog.gif">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="Images\silkBoxed.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="Images\silkSpecular.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Update="Images\texture.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    
</Project>
