<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsBrowserBuild>true</IsBrowserBuild>
    <EmccExtraLDFlags>$(EmccExtraLDFlags) --js-library="$(MSBuildThisFileDirectory)\SkiaSharpGLInterop.js"</EmccExtraLDFlags>
    <PublishTrimmed>true</PublishTrimmed>
    <WasmBuildNative>true</WasmBuildNative>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Drawie2Sample\Drawie2Sample.csproj" />
    <ProjectReference Include="..\DrawiEngine.Browser\DrawiEngine.Browser.csproj"/>
    <ProjectReference Include="..\DrawiEngine\DrawiEngine.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\scripts\drawie.js" />
  </ItemGroup>
</Project>
